---
version: "3.7"

networks:
  frontend:
    driver: bridge
    external:
      name: frontend

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 43200
    restart: unless-stopped
    networks:
      - frontend
