---
variables:
  VERSION: "v6.0"

stages:
    - check_bugfix
    - after_merge_success
    - check_master

# #### Templates - BoF
.tmpl_check: &tmpl_check
    script:
        - |
            for script in $(find ${CI_PROJECT_DIR}/ci/scripts/ -type f -name "[0-9][0-9]-*.bsh" | sort -n); do
                . ${script}
            done
# #### Templates - EoF

# #### Project check (merge request, schedules & triggered)
check_bugfix:
    image: ${REGISTRY_IMAGES}:${VERSION}
    stage: check_bugfix
    only:
      refs:
        - merge_requests
        - schedules
    <<: *tmpl_check

after_merge_success:
    stage: after_merge_success
    only:
      refs:
        - merge_requests
        - schedules
    when: on_success
    script:
        - "curl -X POST -F token=${TRIGGER_TOKEN} -F ref=${VERSION} https://gitlab.com/api/v4/projects/8181679/trigger/pipeline"

check_master:
    image: ${REGISTRY_IMAGES}:${VERSION}
    stage: check_master
    only:
        - triggers
    <<: *tmpl_check
