---
stages:
    - check
    - build_images

# #### Project check (merge request)
Project check:
    image: registry.gitlab.com/toulousain79/mysb_images/project_check/project_check:latest
    stage: check
    only:
      refs:
        - merge_requests
        - schedules
    except:
      variables:
        - $BUILD == "True"
    script:
        - |
            for script in $(echo ${CI_PROJECT_DIR}/ci/scripts/[0-9][0-9]-*.bsh); do
                . ${script}
            done
