---
stages:
    - project_check

# #### Templates - BoF
.tmpl_check: &tmpl_check
    script:
        - |
            for script in $(find ${CI_PROJECT_DIR}/ci/scripts/ -type f -name "[0-9][0-9]-*.bsh" | sort -n); do
                . ${script}
            done
# #### Templates - EoF

# #### Project check (merge request & schedules)
Project check:
    image: registry.gitlab.com/toulousain79/mysb_images/project_check/project_check:v6.0
    stage: project_check
    only:
      refs:
        - merge_requests
        - schedules
    <<: *tmpl_check
