---
variables:
  VERSION: "v6.0"

stages:
    - check_bugfix
    - check_master

# #### Templates - BoF
.tmpl_check: &tmpl_check
    script:
        - |
            for script in $(find ${CI_PROJECT_DIR}/ci/scripts/ -type f -name "[0-9][0-9]-*.bsh" | sort -n); do
                . ${script}
            done
# #### Templates - EoF

# #### Project check (merge request, schedules & triggered)
check_bugfix:
    image: ${REGISTRY_IMAGES}:${VERSION}
    stage: check_bugfix
    only:
      refs:
        - merge_requests
        - schedules
    after_script:
        - "curl -X POST -F token=${TRIGGER_TOKEN} -F ref=${VERSION} https://gitlab.com/api/v4/projects/8181679/trigger/pipeline"
    <<: *tmpl_check

check_master:
    image: ${REGISTRY_IMAGES}:${VERSION}
    stage: check_master
    only:
        - triggers
    when:
        - on_success
        - delayed
    start_in: 20 seconds
    <<: *tmpl_check
