---
stages:
    - check_bugfix
    - check_master

# #### Templates - BoF
.tmpl_check: &tmpl_check
    script:
        - |
            for script in $(find ${CI_PROJECT_DIR}/ci/scripts/ -type f -name "[0-9][0-9]-*.bsh" | sort -n); do
                . ${script}
            done
# #### Templates - EoF

# #### Project check (merge request & schedules)
Check bugfix:
    image: registry.gitlab.com/toulousain79/mysb_images/project_check/project_check:v6.0
    stage: check_bugfix
    only:
      refs:
        - merge_requests
        - schedules
    # after_script:
    #     - "curl -X POST -F token=$TRIGGER_TOKEN -F ref=v6.0 https://gitlab.com/api/v4/projects/toulousain79/MySB/trigger/pipeline"
    <<: *tmpl_check

# Check master:
#     image: registry.gitlab.com/toulousain79/mysb_images/project_check/project_check:v6.0
#     stage: check_master
#     only:
#         - triggers
#     when:
#         - on_success
#     <<: *tmpl_check
