---
stages:
    - check_develop
    - check_master

# #### Templates - BoF
.tmpl_check: &tmpl_check
    script:
        - |
            for script in $(find ${CI_PROJECT_DIR}/ci/scripts/ -type f -name "[0-9][0-9]-*.bsh" | sort -n); do
                . ${script}
            done
# #### Templates - EoF


# #### Project check (merge request)
project_check_develop:
    stage: check_develop
    only:
      refs:
        - schedules
    except:
        - master
    allow_failure: false
    image: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/mysb_images/project_check/project_check:develop
    <<: *tmpl_check


# #### Project check for master branch (after merge request & schedules)
project_check_master:
    stage: check_master
    only:
      refs:
        - master
        - schedules
        - merge_requests
    when: on_success
    allow_failure: false
    image: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/mysb_images/project_check/project_check:v6.0
    <<: *tmpl_check
