---
stages:
  - scheduled_check_bugfix_basic
  - scheduled_check_bugfix_integ

  - scheduled_check_develop_basic
  - scheduled_check_develop_integ

  - scheduled_check_prod_basic
  - scheduled_check_prod_integ

  - scheduled_check_master_basic
  - scheduled_check_master_integ

  - check_bugfix_before_merge_basic
  - check_bugfix_before_merge_integ

  - check_master_after_merge_basic
  - check_master_after_merge_integ

# #### Templates - BoF
.tmpl_check: &tmpl_check
  image: ${REGISTRY_IMAGES}
  script:
    - |
      echo ${CI_PROJECT_DIR}/ci/common/00-libs.sh
      . ${CI_PROJECT_DIR}/ci/common/00-libs.sh
      for script in $(find ${CI_PROJECT_DIR}/ci/${CHECK_DIR}/ -type f -name "[0-9][0-9]-*.sh" | sort -n); do
          echo ${script}
      done
      echo ${CI_PROJECT_DIR}/ci/common/999-end_script.sh

      for script in $(find ${CI_PROJECT_DIR}/ci/${CHECK_DIR}/ -type f -name "[0-9][0-9]-*.sh" | sort -n); do
          . ${script}
      done
      . ${CI_PROJECT_DIR}/ci/common/999-end_script.sh
# #### Templates - EoF

# #### Project check scheduled - BoF
Scheduled Bugfix Basic Tests:
  stage: scheduled_check_bugfix_basic
  variables:
    CHECK_DIR: 'basic'
  only:
    refs:
      - schedules
      - bugfix
    variables:
      - $RELEASE == "bugfix"
  <<: *tmpl_check

Scheduled Bugfix Integ Tests:
  stage: scheduled_check_bugfix_integ
  variables:
    CHECK_DIR: 'integ'
  only:
    refs:
      - schedules
      - bugfix
    variables:
      - $RELEASE == "bugfix"
  <<: *tmpl_check
  when: on_success

Scheduled Develop Basic Tests:
  stage: scheduled_check_develop_basic
  variables:
    CHECK_DIR: 'basic'
  only:
    refs:
      - schedules
      - v99.99
    variables:
      - $RELEASE == "develop"
  <<: *tmpl_check

Scheduled Develop Integ Tests:
  stage: scheduled_check_develop_integ
  variables:
    CHECK_DIR: 'integ'
  only:
    refs:
      - schedules
      - v99.99
    variables:
      - $RELEASE == "develop"
  <<: *tmpl_check
  when: on_success

ProdBasic Tests:
  stage: scheduled_check_prod_basic
  variables:
    CHECK_DIR: 'basic'
  only:
    refs:
      - schedules
      - v7.3
    variables:
      - $RELEASE == "prod"
  <<: *tmpl_check

ProdInteg Tests:
  stage: scheduled_check_prod_integ
  variables:
    CHECK_DIR: 'integ'
  only:
    refs:
      - schedules
      - v7.3
    variables:
      - $RELEASE == "prod"
  <<: *tmpl_check
  when: on_success

Scheduled Prod Basic Tests:
  stage: scheduled_check_master_basic
  variables:
    CHECK_DIR: 'basic'
  only:
    refs:
      - schedules
      - v7.3
    variables:
      - $RELEASE == "prod"
  <<: *tmpl_check

Scheduled Prod Integ Tests:
  stage: scheduled_check_master_integ
  variables:
    CHECK_DIR: 'integ'
  only:
    refs:
      - schedules
      - v7.3
    variables:
      - $RELEASE == "prod"
  <<: *tmpl_check
  when: on_success
# #### Project check scheduled - EoF

# #### Project check merge request - BoF
Bugfix Basic Tests:
  stage: check_bugfix_before_merge_basic
  variables:
    CHECK_DIR: 'basic'
  only:
    refs:
      - merge_requests
  <<: *tmpl_check

Bugfix Integ Tests:
  stage: check_bugfix_before_merge_integ
  variables:
    CHECK_DIR: 'integ'
  only:
    refs:
      - merge_requests
  when: on_success
  <<: *tmpl_check

Prod Basic Tests:
  stage: check_master_after_merge_basic
  variables:
    CHECK_DIR: 'basic'
  <<: *tmpl_check
  only:
    - v7.3
  except:
    - schedules
  when: on_success

Prod Integ Tests:
  stage: check_master_after_merge_integ
  variables:
    CHECK_DIR: 'integ'
  <<: *tmpl_check
  only:
    - v7.3
  except:
    - schedules
  when: on_success
# #### Project check merge request - EoF
