---
stages:
    - check
    - build_images

# #### Project check (merge request)
Project check:
    image: ${CI_REGISTRY_IMAGE}/project_check/project_check:latest
    stage: check
    only:
      refs:
        - merge_requests
        - schedules
      variables:
        - $CHECK == "True"
    script:
        - |
            for script in $(echo ${CI_PROJECT_DIR}/ci/scripts/*.bsh); do
                ([ "${script}" != "100-start_build.bsh" ] && [ "${script}" != "999-docker_clean.bsh" ]) && . ${script}
            done

# #### BUILD
Building Docker Images:
    image: docker:dind
    stage: build_images
    only:
      refs:
        - schedules
      variables:
        - $BUILD == "True"
    services:
        - docker:dind
    variables:
        DOCKER_HOST: tcp://docker:2375
        DOCKER_DRIVER: overlay2
    before_script:
        - apk add bash
        - docker version
        - echo $HUB_PASSWORD | docker login -u $HUB_USER --password-stdin
        - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
    script:
        - bash ${CI_PROJECT_DIR}/ci/scripts/100-start_build.bsh
    after_script:
        - docker logout ${CI_REGISTRY}
        - docker logout
